export const HIE_CONSENT = {
  NATIONAL_ID: 'National ID',
  SHARED_HEALTH_RECORD: 'SHARED_HEALTH_RECORD',
  CLIENT_REGISTRY: 'CLIENT_REGISTRY',
  OTP_LENGTH: 5,
  OTP_VALIDATION_DEBOUNCE: 400,
  KENYAN_PHONE_REGEX: /^(?:\+254|254|0)\d{9}$/,
};
